apiVersion: v1
kind: Secret
metadata:
  namespace: logging
  name: elastic
type: kubernetes.io/basic-auth
stringData:
  username: elastic
  password:
---
apiVersion: v1
kind: Secret
metadata:
  namespace: logging
  name: elasticsearch-keystore
stringData:
  ca-password:
  transport-password:
  http-password:
