apiVersion: v1
kind: Secret
metadata:
  namespace: logging
  name: elastic
type: kubernetes.io/basic-auth
stringData:
  username: elastic
  password: wR3feWXhJdXamsadPBFC7Czfszpe9uhx
---
apiVersion: v1
kind: Secret
metadata:
  namespace: logging
  name: elasticsearch-keystore
stringData:
  ca-password: APQTLj6ECLEiJQoaQrqb4hogqC3cqeQw
  transport-password: yDJWBpn2bW7XVGgXygQWNpazYzHH6Y8m
  http-password: ut9AH7iknu4gypyyhe8bJ6Xhv3BL4ufB
