apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    protocol: TCP
    targetPort: elastic-https
