apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
  - port: 9100
    protocol: TCP
    targetPort: prom-node-http
