filebeat.inputs:
- type: container
  paths:
    - /var/log/containers/*.log
  processors:
    - add_host_metadata:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
output.logstash:
  hosts: ["logstash.logging:5044"]
