apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
generatorOptions:
  disableNameSuffixHash: true
resources:
- daemonset.yaml
- serviceaccount.yaml
configMapGenerator:
- name: filebeat-config
  files:
  - filebeat.yml
