apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: infrastructure
  labels:
    app: git
spec:
  type: NodePort
  selector:
    app: git
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: ssh
    - name: git
      port: 9418
      protocol: TCP
      targetPort: git
