apiVersion: v1
kind: Service
metadata:
  name: git-ephemeral
  namespace: infrastructure
  labels:
    app: git-ephemeral
spec:
  type: NodePort
  selector:
    app: git-ephemeral
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: ssh
