apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
  namespace: infrastructure
  labels:
    app: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      initContainers:
      - name: ssh-init
        image: registry.convex.watsonkp.com/sulliedeclat/ssh-init:latest
        imagePullPolicy: Always
        env:
        - name: IDENTITY
          valueFrom:
            configMapKeyRef:
              name: git-ssh-config
              key: git-ssh.identity
        command: ['/bin/sh', '/container/server-init.sh']
        volumeMounts:
        - name: key
          mountPath: "/key"
          readOnly: false
        - name: ca
          mountPath: "/secret"
          readOnly: true
      containers:
        - name: git-ssh
          image: registry.convex.watsonkp.com/sulliedeclat/git-ssh:0.3
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          ports:
          - containerPort: 22
            name: ssh
          volumeMounts:
          - name: ssh
            mountPath: "/etc/ssh"
            readOnly: true
          - name: gitconfig
            mountPath: "/etc/gitconfig"
            subPath: gitconfig
            readOnly: true
          - name: key
            mountPath: "/key"
            readOnly: true
          - name: repositories
            mountPath: "/srv/git"
            readOnly: false
        - name: git-git
          image: registry.convex.watsonkp.com/sulliedeclat/git-git:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 9418
            name: git
          volumeMounts:
          - name: repositories
            mountPath: "/srv/git"
            readOnly: true
      volumes:
      - name: ssh
        projected:
          sources:
          - configMap:
              name: sshd-config
          - configMap:
              name: ca-user-key-public
      - name: gitconfig
        configMap:
          name: gitconfig
      - name: ca
        secret:
          secretName: ca-host-key
          defaultMode: 256
      - name: key
        emptyDir:
          sizeLimit: 10Mi
      - name: repositories
        emptyDir:
          sizeLimit: 500Mi
