apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
- git.yaml
- backup.yaml
- config.yaml
configMapGenerator:
- name: gitconfig
  files:
    - config/git/gitconfig
- name: sshd-config
  files:
    - config/git/sshd_config
