apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: infrastructure
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - distribution.svc.cluster.local
    secretName: distribution-tls
  rules:
  - host: youtrack.infrastructure.svc.cluster.local
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: youtrack
              port:
                number: 8080
  - host: jenkins.infrastructure.svc.cluster.local
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: jenkins
              port:
                number: 8080
  - host: distribution.infrastructure.svc.cluster.local
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: distribution
              port:
                number: 80
