apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
- ingress.yaml
patches:
- target:
    kind: Ingress
    name: ingress
    namespace: infrastructure
  path: set_host.yaml
