apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
generatorOptions:
  disableNameSuffixHash: true
resources:
- service.yaml
- kibana.yaml
- credentials.yaml
configMapGenerator:
- name: init-kibana-users
  files:
  - users.sh
patches:
- target:
    kind: Deployment
    name: kibana
    namespace: logging
  path: set_registry.yaml
