apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
  - port: 5601
    protocol: TCP
    targetPort: kibana-http
