apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - port: 3000
    protocol: TCP
    targetPort: grafana-http
