apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
- ingress.yaml
- ingress-https.yaml
patches:
- target:
    kind: Ingress
    name: logging
    namespace: logging
  path: set_ingress_host.yaml
- target:
    kind: Ingress
    name: logging-https
    namespace: logging
  path: set_ingress_https_host.yaml
