apiVersion: v1
kind: Secret
metadata:
  namespace: logging
  name: filebeat-installer
type: kubernetes.io/basic-auth
stringData:
  username: filebeat_installer
  password: NHPg6t2jh8wHGpYgzahknQGEAa44v2x4
