apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
generatorOptions:
  disableNameSuffixHash: true
resources:
- setup.yaml
- credentials.yaml
configMapGenerator:
- name: init-filebeat-setup-users
  files:
  - users.sh
patches:
- target:
    kind: Job
    name: filebeat-setup
    namespace: logging
  path: set_registry.yaml
