apiVersion: v1
kind: Secret
metadata:
  name: distribution-tls
  namespace: infrastructure
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
type: kubernetes.io/tls
