apiVersion: apps/v1
kind: Deployment
metadata:
  name: distribution
  namespace: infrastructure
  labels:
    app: distribution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distribution
  template:
    metadata:
      labels:
        app: distribution
    spec:
      initContainers:
      - name: ssh-init
        image: registry.infrastructure.svc.cluster.local/example/ssh-init:latest
        imagePullPolicy: Always
        env:
        - name: IDENTITY
          valueFrom:
            configMapKeyRef:
              name: dist-ssh-config
              key: dist-ssh.identity
        command: ['/bin/sh', '/container/server-init.sh']
        volumeMounts:
        - name: key
          mountPath: "/key"
          readOnly: false
        - name: ca
          mountPath: "/secret"
          readOnly: true
      containers:
        - name: dist-ssh
          image: registry.infrastructure.svc.cluster.local/example/ssh:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          ports:
          - containerPort: 22
            name: dist-ssh
          volumeMounts:
          - name: ssh
            mountPath: "/etc/ssh"
            readOnly: true
          - name: key
            mountPath: "/key"
            readOnly: true
          - name: builds
            mountPath: "/usr/share/nginx/html"
            readOnly: false
        - name: dist-web
          image: docker.io/library/nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
            name: dist-http
          volumeMounts:
          - name: builds
            mountPath: "/usr/share/nginx/html"
            readOnly: true
      volumes:
      - name: ssh
        projected:
          sources:
          - configMap:
              name: sshd-config
          - configMap:
              name: ca-user-key-public
      - name: ca
        secret:
          secretName: ca-host-key
          defaultMode: 256
      - name: key
        emptyDir:
          sizeLimit: 10Mi
      - name: builds
        emptyDir:
          sizeLimit: 512Mi
