apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - github.com/metallb/metallb/config/native?ref=v0.13.10
  - ipaddresspool.yaml
patches:
- target:
    kind: IPAddressPool
    name: pool
    namespace: metallb-system
  path: set_pool.yaml
