apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  type: NodePort
  selector:
    app: cadvisor
  ports:
  - port: 8080
    protocol: TCP
    targetPort: cadvisor-http
