apiVersion: v1
kind: Service
metadata:
  name: youtrack
  namespace: infrastructure
  labels:
    app: youtrack
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: youtrack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: youtrack-http
