apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  config: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: 'prometheus.monitoring.svc.cluster.local'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: crio
        scrape_interval: 5s
        static_configs:
          - targets: ['kube-node0:9090', 'kube-node1:9090']
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'cadvisor'
          action: keep
      - job_name: kube-state-metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
