apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - port: 9090
    protocol: TCP
    targetPort: prometheus-http
