apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: prometheus-http
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: config
              mountPath: /config/prometheus
            - name: storage
              mountPath: /data/prometheus
          args:
            - '--storage.tsdb.retention.time=7d'
            - '--storage.tsdb.retention.size=4GB'
            - '--storage.tsdb.path=/data/prometheus'
            - '--config.file=/config/prometheus/prometheus.yaml'
      volumes:
        - name: storage
          emptyDir:
            sizeLimit: 5Gi
        - name: config
          configMap:
            name: prometheus-config
            items:
              - key: "config"
                path: "prometheus.yaml"

