apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
generatorOptions:
  disableNameSuffixHash: true
resources:
- service.yaml
- deployment.yaml
- credentials.yaml
configMapGenerator:
- name: logstash-config
  files:
  - logstash.yml
- name: logstash-log4j2
  files:
  - log4j2.properties
- name: logstash-pipelines
  files:
  - pipelines.yml
- name: logstash-beats-pipeline
  files:
  - beats-pipeline.conf
- name: init-logstash-users
  files:
  - users.sh
patches:
- target:
    kind: Deployment
    name: logstash
    namespace: logging
  path: set_registry.yaml
