apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jenkins.yaml
namespace: infrastructure
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: jenkins-plugins
  files:
  - plugins.txt
- name: jenkins-executors
  files:
  - executors.groovy
- name: artifacts-index
  files:
  - index.tmpl
- name: artifacts-style
  files:
  - main.css
- name: measure-display-image
  files:
  - measure.512x512.png
- name: measure-full-size-image
  files:
  - measure.57x57.png
patches:
- target:
    kind: Deployment
    name: jenkins
    namespace: infrastructure
  path: set_registry.yaml
