apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jenkins.yaml
namespace: infrastructure
configMapGenerator:
- name: jenkins-plugins
  files:
  - plugins.txt
- name: jenkins-executors
  files:
  - executors.groovy
