apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: infrastructure
  labels:
    app: jenkins
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
  - name: jenkins-http
    port: 8080
    protocol: TCP
    targetPort: jenkins-http
  - name: artifact-http
    port: 8081
    protocol: TCP
    targetPort: artifact-http
